package com.exe;

public class TestException {
	
	public static void main(String args[]) {
		try {
		int no1 = Integer.parseInt(args[0]);
		int no2 = Integer.parseInt(args[1]);
		String op = args[2];
		
		double res = no1/no2;
		System.out.println("Result is:"+res);
	}
	catch(ArithmeticException ex) {
		ex.printStackTrace();
	}
	catch(ArrayIndexOutOfBoundsException ex) {
		System.out.println(ex.getMessage());
	}
	}		

}
